spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:${DATABASE_HOST:localhost}}:${DB_PORT:5432}/${DB_NAME:neondb}?sslmode=${DB_SSLMODE:require}&channelBinding=${DB_CHANNELBINDING:disable}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${APP_PORT:8080}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true