package com.example.backend.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.time.LocalDateTime;

public class TaskTest {

    @Test
    public void testTaskConstructorAndGetters() {
        Event event = new Event("Test Event", LocalDateTime.now(), LocalDateTime.now().plusHours(1));
        Task task = new Task("Test Task", 60, 1, event);

        assertNull(task.getId()); // Id is generated by persistence layer
        assertEquals("Test Task", task.getTitle());
        assertEquals(60, task.getEstimatedDuration());
        assertEquals(1, task.getPriority());
        assertEquals(event, task.getEvent());
    }

    @Test
    public void testTaskSetters() {
        Task task = new Task();
        Event event = new Event("New Event", LocalDateTime.now(), LocalDateTime.now().plusHours(2));

        task.setTitle("Updated Task");
        task.setEstimatedDuration(90);
        task.setPriority(2);
        task.setEvent(event);

        assertEquals("Updated Task", task.getTitle());
        assertEquals(90, task.getEstimatedDuration());
        assertEquals(2, task.getPriority());
        assertEquals(event, task.getEvent());
    }
}
