name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build backend (Gradle)
        run: |
          cd backend
          ./gradlew build

      - name: Build frontend (React)
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
